---
apiVersion: v2
appVersion: v0.0.3
description: A Helm chart for Identity-API - RFC 8693 token exchange server.
name: identity-api
keywords:
version: v0.0.3
home: http://github.com/infratographer/identity-api
dependencies:
  - name: common
    version: 2.2.3
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Adam Mohammed
    url: https://github.com/adammohammed
    email: admohammed@equinix.com
