---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.names.fullname" . -}}
{{- if empty .Values.ingress.hosts }}
{{- fail ".Values.ingress.hosts must contain at least one entry" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $fullName }}-ingress
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host  | quote }}
      http:
        paths:
          {{- range (.paths | default (list "/")) }}
          - pathType: {{ $.Values.ingress.pathType | default "Prefix" | quote }}
            path: {{ . | quote }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: web
  {{- end }}
  {{- end }}
  {{- with .Values.ingress }}
  tls:
    {{- toYaml .tls | nindent 4 }}
  {{- end }}
{{- end }}
